
version: 2

models:
    - name: first_test
      description: "A starter dbt model"
      columns:
          - name: primary key
            description: "The primary key for this table"
            tests:
                - unique
                - not_null


